edit_uri: 'blob/main/docs/'
site_name: Computers West
site_url: https://computerswest.org/
repo_name: dwighthubbard/computerswest
repo_url: https://github.com/dwighthubbard/computerswest
extra:
  generator: false
theme:
  # name: mkdocs
  name: material
  logo: images/cw-logo-clear8-e1711862350250.png
  favicon: images/favicon.ico
  # user_color_mode_toggle: true
  # include_sidebar: true
  icon:
    edit: material/pencil 
    view: material/eye
  features:
    # - navigation.sections
    # - navigation.path
    - toc.integrate
    - navigation.tabs
    # - navigation.instant
    - content.action.edit
  palette:
    primary: custom

extra_css:
  - stylesheets/theme.css

exclude_docs: |
  sigs/3d-printing/classes/*/deck/*.md

markdown_extensions:
    - pymdownx.blocks.html
    - admonition
    - footnotes
    - def_list
    - attr_list
    - md_in_html
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.critic
    - pymdownx.keys
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.superfences
    - toc:
        permalink: true

plugins:
  git-authors:
    enabled: true
    repository: dwighthubbard/computerswest
    branch: main
  # git-committers:
  #   enabled: true
  #   repository: dwighthubbard/computerswest
  #   branch: main
  git-revision-date-localized:
    enable_creation_date: true
    fallback_to_build_date: true
  slides:
    template: docs/sigs/3d-printing/classes/introduction/slide-template.html
  search:
    enabled: true

nav:
  - Home: index.md
  # - About:
  #     - History: about/history.md
  #     - Cell Phones for Soldiers: about/cell-phones-for-soldiers.md
  # - Membership:
  #     - Membership Info: membership/index.md
  #     - Calendar: membership/calendar.md
  #     - Newsletters: membership/newsletters.md
  #     - Officers: membership/officers.md
  #     - Meeting Minutes: membership/minutes.md
  #     - Bylaws: membership/bylaws.md
  # - Monitor Signup & Training:
  #     - Monitor Signup: monitor/signup.md
  #     - Monitor Duties: monitor/duties.md
  #     - "Monitor Training & Orientation": monitor/training.md
  #     - Monitoring Manual: monitor/manual.md
  # - "Technology Support & Repair": tech-support/index.md
  # - Classes:
  #     - Overview: classes/overview.md
  #     - Registration: classes/registration.md
  #     - FAQs: classes/faqs.md
  # - Special Interest Groups:
  #     - Overview: sigs/overview.md
  #     - 3D Printing:
  - 3d Printing: sigs/3d-printing/3d-printing.md
  - 3D Printing Classes:
      - Introduction:
          - Overview: sigs/3d-printing/classes/introduction/index.md
          - Slide Deck: sigs/3d-printing/classes/introduction/slide-deck.md
      - Getting Models:
          - Overview: sigs/3d-printing/classes/Getting Models/index.md
          - Slide Deck: sigs/3d-printing/classes/Getting Models/slide-deck.md
      - Slicing:
          - Overview: sigs/3d-printing/classes/Slicing/index.md
          - Slide Deck: sigs/3d-printing/classes/Slicing/slide-deck.md
      - Materials:
          - Overview: sigs/3d-printing/classes/Materials/index.md
          - Slide Deck: sigs/3d-printing/classes/Materials/slide-deck.md
      - Parametric Design:
          - Overview: sigs/3d-printing/classes/Parametric Design/index.md
          - Slide Deck: sigs/3d-printing/classes/Parametric Design/slide-deck.md
      - AI Design:
          - Overview: sigs/3d-printing/classes/AI Design/index.md
          - Slide Deck: sigs/3d-printing/classes/AI Design/slide-deck.md
      - Common Problems and Solutions:
          - Overview: sigs/3d-printing/classes/Common Problems and Solutions/index.md
          - Slide Deck: sigs/3d-printing/classes/Common Problems and Solutions/slide-deck.md
      - Designing For 3D Printing:
          - Overview: sigs/3d-printing/classes/Designing For 3D Printing/index.md
          - Slide Deck: sigs/3d-printing/classes/Designing For 3D Printing/slide-deck.md
      - Functional Parts and Repairs:
          - Overview: sigs/3d-printing/classes/Functional Parts and Repairs/index.md
          - Slide Deck: sigs/3d-printing/classes/Functional Parts and Repairs/slide-deck.md
      - Post Processing:
          - Overview: sigs/3d-printing/classes/Post Processing/index.md
          - Slide Deck: sigs/3d-printing/classes/Post Processing/slide-deck.md
      - Maintenance and Calibration:
          - Overview: sigs/3d-printing/classes/Maintenance and Calibration/index.md
          - Slide Deck: sigs/3d-printing/classes/Maintenance and Calibration/slide-deck.md
      - 3D Scanning and Reverse Engineering:
          - Overview: sigs/3d-printing/classes/3D Scanning and Reverse Engineering/index.md
          - Slide Deck: sigs/3d-printing/classes/3D Scanning and Reverse Engineering/slide-deck.md
  #     - All Things Apple: sigs/apple.md
  #     - Artificial Intelligence: sigs/ai.md
  #     - Streaming and Cord Cutting: sigs/streaming-cord-cutting.md
  #     - Flight Simulator: sigs/flight-simulator.md
  #     - Genealogy: sigs/genealogy.md
  #     - "Open Systems (Linux)": sigs/open-systems.md
  #     - PC Windows: sigs/windows.md
  #     - Video Hangouts: sigs/video-hangouts.md
  # - Pay Dues: pay-dues.md
